---
groups:
  - name: bosh-vsphere-cpi-release
    jobs:
      - build-candidate
      - deploy-ubuntu-manual
      - bats-ubuntu-manual
      - deploy-centos-manual
      - bats-centos-manual
      - lifecycle

  - name: ubuntu
    jobs:
      - build-candidate
      - deploy-ubuntu-manual
      - bats-ubuntu-manual

  - name: centos
    jobs:
      - build-candidate
      - deploy-centos-manual
      - bats-centos-manual

jobs:
  - name: build-candidate
    serial: true
    plan:
      - aggregate:
          - {trigger: true,  get: bosh-cpi-release}
          - {trigger: false, get: version-semver,   params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: build/out/.*\.tgz}

  - name: lifecycle
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: bosh-src}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        config:
          tags: ["vsphere"]
          params:
            BOSH_VSPHERE_CPI_HOST: {{lifecycle_BOSH_VSPHERE_CPI_HOST}}
            BOSH_VSPHERE_CPI_USER: {{lifecycle_BOSH_VSPHERE_CPI_USER}}
            BOSH_VSPHERE_CPI_PASSWORD: {{lifecycle_BOSH_VSPHERE_CPI_PASSWORD}}
            BOSH_VSPHERE_VLAN: {{lifecycle_BOSH_VSPHERE_VLAN}}
            BOSH_VSPHERE_CPI_DATACENTER: {{lifecycle_BOSH_VSPHERE_CPI_DATACENTER}}
            BOSH_VSPHERE_CPI_CLUSTER: {{lifecycle_BOSH_VSPHERE_CPI_CLUSTER}}
            BOSH_VSPHERE_CPI_DATASTORE_PATTERN:  {{lifecycle_BOSH_VSPHERE_CPI_DATASTORE_PATTERN}}
            BOSH_VSPHERE_CPI_PERSISTENT_DATASTORE_PATTERN: {{lifecycle_BOSH_VSPHERE_CPI_PERSISTENT_DATASTORE_PATTERN}}
            BOSH_VSPHERE_CPI_SECOND_DATASTORE: {{lifecycle_BOSH_VSPHERE_CPI_SECOND_DATASTORE}}
            BOSH_VSPHERE_CPI_RESOURCE_POOL: {{lifecycle_BOSH_VSPHERE_CPI_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL: {{lifecycle_BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER: {{lifecycle_BOSH_VSPHERE_CPI_SECOND_CLUSTER}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE: {{lifecycle_BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL: {{lifecycle_BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_VM_FOLDER: {{lifecycle_BOSH_VSPHERE_CPI_VM_FOLDER}}
            BOSH_VSPHERE_CPI_TEMPLATE_FOLDER: {{lifecycle_BOSH_VSPHERE_CPI_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_CPI_DISK_PATH: {{lifecycle_BOSH_VSPHERE_CPI_DISK_PATH}}

  - name: deploy-ubuntu-manual
    serial_groups: [ubuntu-director-manual] # shouldn't deploy while bats are running
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: bosh-concourse-ci }
        - {trigger: false,                            get: bosh-init}
        - {trigger: false,                            get: bosh-release}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell}

      - task: deploy
        file: bosh-cpi-release/ci/tasks/deploy.yml
        config:
          tags: ["vsphere"]
          params:
            base_os: ubuntu
            network_type_to_test: manual

      - conditions: [success, failure]
        task: save-deployment
        file: bosh-cpi-release/ci/tasks/save-deployment.yml
        config:
          params:
            base_os: ubuntu
            network_type_to_test: manual

      - put: bosh-concourse-ci
        params:
          repository: save-deployment/deploy/bosh-concourse-ci
          rebase: true

  - name: bats-ubuntu-manual
    serial_groups: [ubuntu-director-manual] # can't run while deploying
    plan:
      - aggregate:
        - {trigger: true,  passed: [deploy-ubuntu-manual], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [deploy-ubuntu-manual], get: bosh-cpi-release}
        - {trigger: false, passed: [deploy-ubuntu-manual], get: stemcell, resource: vsphere-ubuntu-stemcell}
        - {trigger: false, passed: [deploy-ubuntu-manual], get: bosh-concourse-ci}
        - {trigger: false,                                 get: bats}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          tags: ["vsphere"]
          params:
            base_os: ubuntu
            network_type_to_test: manual

  - name: deploy-centos-manual
    serial_groups: [centos] # shouldn't deploy while bats are running
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: bosh-concourse-ci }
        - {trigger: false,                            get: bosh-init}
        - {trigger: false,                            get: bosh-release}
        - {trigger: false,                            get: stemcell, resource: vsphere-centos-stemcell}

      - task: deploy
        file: bosh-cpi-release/ci/tasks/deploy.yml
        config:
          tags: ["vsphere"]
          params:
            base_os: centos
            network_type_to_test: manual

      - conditions: [success, failure]
        task: save-deployment
        file: bosh-cpi-release/ci/tasks/save-deployment.yml
        config:
          params:
            base_os: centos
            network_type_to_test: manual

      - put: bosh-concourse-ci
        params:
          repository: save-deployment/deploy/bosh-concourse-ci
          rebase: true

  - name: bats-centos-manual
    serial_groups: [centos-director-manual] # can't run while deploying
    plan:
      - aggregate:
        - {trigger: true,  passed: [deploy-centos-manual], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [deploy-centos-manual], get: stemcell, resource: vsphere-centos-stemcell}
        - {trigger: false, passed: [deploy-centos-manual], get: bosh-concourse-ci}
        - {trigger: false, passed: [deploy-centos-manual], get: bosh-cpi-release}
        - {trigger: false,                                 get: bats}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          tags: ["vsphere"]
          params:
            base_os: centos
            network_type_to_test: manual

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-vsphere-cpi\.tgz
      bucket: bosh-vsphere-cpi-release
      region_name: us-east-1
      access_key_id:     {{s3_vsphere_cpi_access_key}}
      secret_access_key: {{s3_vsphere_cpi_secret_key}}

  - name: bosh-cpi-release
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}

  - name: bosh-concourse-ci
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-concourse-ci.git
      branch: master
      private_key: {{github_deployment_key__bosh-concourse-ci}}

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            bosh-vsphere-cpi-release
      access_key_id:     {{s3_vsphere_cpi_access_key}}
      secret_access_key: {{s3_vsphere_cpi_secret_key}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: master

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: vsphere-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: vsphere-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: concourse
