---
jobs:
  - name: e2e-test-centos
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: bosh-release, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: stemcell, resource: vsphere-centos-stemcell, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-init, tags: ["vsphere-v5.1"]}

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          acquire: true

      - task: show_env
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/show_env.yml

      - task: setup-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VERSION:                   {{VSPHERE_VERSION}}
            BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}
            BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{e2e_centos_VCENTER_VM_FOLDER}}
            BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{e2e_centos_VCENTER_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_VCENTER_DISK_PATH:         {{e2e_centos_VCENTER_DISK_PATH}}
            BOSH_DIRECTOR_USERNAME:                 {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:                 {{BOSH_DIRECTOR_PASSWORD}}

      - task: deploy-dummy
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            director_username:                      {{BOSH_DIRECTOR_USERNAME}}
            director_password:                      {{BOSH_DIRECTOR_PASSWORD}}
            stemcell_name:                          {{centos_STEMCELL_NAME}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}

      - task: teardown-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          release: vsphere-5.1-environment

  - name: e2e-test-ubuntu
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: bosh-release, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-init, tags: ["vsphere-v5.1"]}

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          acquire: true

      - task: show_env
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/show_env.yml

      - task: setup-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params: &ubuntu-director-params
            BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VERSION:                   {{VSPHERE_VERSION}}
            BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}
            BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{e2e_ubuntu_VCENTER_VM_FOLDER}}
            BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{e2e_ubuntu_VCENTER_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_VCENTER_DISK_PATH:         {{e2e_ubuntu_VCENTER_DISK_PATH}}
            BOSH_DIRECTOR_USERNAME:                 {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:                 {{BOSH_DIRECTOR_PASSWORD}}

      - task: deploy-dummy
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            director_username:                      {{BOSH_DIRECTOR_USERNAME}}
            director_password:                      {{BOSH_DIRECTOR_PASSWORD}}
            stemcell_name:                          {{ubuntu_STEMCELL_NAME}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}

      - task: teardown-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          release: vsphere-5.1-environment

  - name: upgrade-test
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: bosh-release, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: bosh-init, tags: ["vsphere-v5.1"]}

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          acquire: true

      - task: show_env
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/show_env.yml

      - task: setup-old-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/setup-old-director.yml
        config:
          params:
            <<: *ubuntu-director-params
            old_bosh_release_version: 229
            old_bosh_release_sha1: caad7d5353a76f81550868c54c6e0b441b378864
            old_vsphere_cpi_release_version: 14
            old_vsphere_cpi_release_sha1: f2bd2e21542cd147d360e89d064a728a89c3790f
            old_bosh_stemcell_name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
            old_bosh_stemcell_version: 3143
            old_bosh_stemcell_sha1: 222a546ccccd971a418d82aa6d3799c010164e9f
            old_bosh_init_version: 0.0.80
            old_bosh_init_sha1: 0801bda67311d24fba5103cbb965b751f1c92cb2

      - task: deploy-dummy
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            delete_deployment_when_done:            false
            director_username:                      {{BOSH_DIRECTOR_USERNAME}}
            director_password:                      {{BOSH_DIRECTOR_PASSWORD}}
            stemcell_name:                          {{ubuntu_STEMCELL_NAME}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}

      - task: test-upgrade
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            director_username:                      {{BOSH_DIRECTOR_USERNAME}}
            director_password:                      {{BOSH_DIRECTOR_PASSWORD}}

      - task: teardown-director
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - put: vsphere-5.1-environment
        tags: ["vsphere-v5.1"]
        params:
          release: vsphere-5.1-environment

resources:
  - name: bosh-cpi-artifacts
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release

  - name: bosh-cpi-src
    type: git
    source:
      uri:         https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release
      branch:      master

  - name: bosh-init
    type: s3
    source:
      regexp:      bosh-init-([0-9.]+)-linux-amd64
      bucket:      {{s3_bosh_init_bucket}}
      region_name: us-east-1

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: vsphere-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: vsphere-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: vsphere-5.1-environment
    type: pool
    source:
      pool: vsphere-5.1
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
